/** Serializable SaturnBot configuration, journal records, and dashboard projections. */
import type { Branded } from '@deepseek-ai/dsh-brand'
import type { BotFirstRun, BotIntegrationCatalogEntry } from './wizard.ts'

/** Stable execution identity generated by the runtime. */
export type BotId = Branded<'SaturnBotId'>
/** JSON values accepted across tools, persistence, and remote calls. */
export type BotJson = null | boolean | number | string | BotJson[] | { [key: string]: BotJson
}
/** Named specialists and the planning role. */
export type BotRole = 'orchestrator' | 'developer' | 'growth' | 'operations' | 'finance'
/** Validated deployment/user configuration; credentials are environment variable names only. */
export interface BotConfig {
  version: 1
  enabled: boolean
  goal: string
  workspace: string
  intervalMinutes: number
  provider: string
  model: string
  maxTasks: number
  maxActionsPerTask: number
  toolTimeoutMs: number
  modelTimeoutMs: number
  maxInputBytes: number
  maxOutputTokens: number
  requirePrApproval: boolean
  autoDispatchEmail: boolean
  requireDeployApproval: boolean
  requireWriteApproval: boolean
  allowedTools: string[]
  roles: Record<BotRole, { enabled: boolean
    instructions: string
    tools: string[] }>
  validationCommands: string[][]
  integrations: Record<string, { endpoint?: string
    credentialEnv?: string
    resource?: string }>
  reportChannel: string
}
/** One bounded task chosen by the orchestrator. */
export interface BotTask {
  id: BotId
  role: Exclude<BotRole, 'orchestrator'>
  title: string
  instruction: string
}
/** Untrusted model tool request, admitted only through the tool's own schema. */
export interface ToolProposal {
  tool: string
  input: Record<string, BotJson>
}
/** A specialist's reviewable plan, never private chain-of-thought. */
export interface AgentProposal {
  summary: string
  actions: ToolProposal[]
  continue?: boolean
}
/** An isolated artifact revision; adapters must publish this exact revision. */
export interface BotStage {
  path: string
  revision: string
}
/** Execution state of one independent specialist branch. */
export interface BotBranch {
  id: BotId
  task: BotTask
  status: 'planning' | 'running' | 'awaiting-approval' | 'completed' | 'failed' | 'interrupted'
  summary: string
  actions: ToolProposal[]
  nextAction: number
  continue: boolean
  rounds: number
  stage: BotStage | null
  validatedRevision: string | null
  error: string | null
}
/** A persisted cycle, including its independently settled branches. */
export interface BotCycle {
  id: BotId
  startedAt: string
  finishedAt: string | null
  status: 'running' | 'awaiting-approval' | 'completed' | 'failed' | 'interrupted'
  plan: string
  branches: BotBranch[]
}
/** Approval binds an exact action and stage; it can be consumed only once. */
export interface BotApproval {
  id: BotId
  cycleId: BotId
  branchId: BotId
  actionIndex: number
  tool: string
  input: Record<string, BotJson>
  stage: BotStage | null
  status: 'pending' | 'approved' | 'rejected' | 'consumed' | 'interrupted'
  createdAt: string
  decidedAt: string | null
}
/** Observable execution facts, excluding credentials and private reasoning. */
export interface BotTrace {
  cycleId: BotId
  branchId: BotId | null
  kind: 'plan' | 'proposal' | 'tool-start' | 'tool-result' | 'tool-error' | 'decision'
  tool?: string
  attempt?: number
  summary: string
  data?: BotJson
}
/** Durable operator-visible problem. */
export interface BotAlert {
  id: BotId
  cycleId: BotId | null
  branchId: BotId | null
  message: string
  createdAt: string
}
/** Markdown report retained in the durable report inbox. */
export interface BotReport {
  id: BotId
  cycleId: BotId
  date: string
  title: string
  markdown: string
  channel: string
}
/** Persisted role conversation, containing user instructions and public summaries. */
export interface BotMessage {
  id: BotId
  role: BotRole
  sender: 'user' | 'agent' | 'system'
  content: string
  at: string
  cycleId: BotId | null
}
/** Reconstructed execution state; bounded dashboard history is selected by the store. */
export interface BotSnapshot {
  config: BotConfig
  status: 'needs-setup' | 'disabled' | 'idle' | 'running' | 'awaiting-approval'
  activeCycle: BotCycle | null
  cycles: BotCycle[]
  approvals: BotApproval[]
  reports: BotReport[]
  alerts: BotAlert[]
  cursor: number
  nextRunAt: string | null
  tools: { name: string
    description: string
    roles: BotRole[]
    effect: string
    enabled: boolean }[]
  connections: { id: string
    status: 'configured' | 'unconfigured'
    detail: string }[]
  messages: BotMessage[]
  /** Wizard-facing summary of the values that gate an initial run. */
  firstRun: BotFirstRun
  /** The static field-level connect-form catalog for every supported integration. */
  integrationCatalog: BotIntegrationCatalogEntry[]
}
/** Append-only state transition payloads. */
export type BotEventData =
  | { type: 'configured'
    config: BotConfig
  }
  | { type: 'cycle'
    cycle: BotCycle
  }
  | { type: 'approval'
    approval: BotApproval
  }
  | { type: 'trace'
    trace: BotTrace
  }
  | { type: 'alert'
    alert: BotAlert
  }
  | { type: 'report'
    report: BotReport
  }
  | { type: 'message'
    message: BotMessage
  }
/** One versioned JSONL journal record. */
export type BotEvent = BotEventData & { version: 1
  seq: number
  at: string
}
/** Cursor-based event page. */
export interface BotEventPage {
  events: BotEvent[]
  cursor: number
  hasMore: boolean
}
