// assets/background-runner.js runs in @capacitor/background-runner's
// isolated JS engine, which cannot use ES module imports (its README's
// "JavaScript API" section) -- so it can't import src/lib/backgroundEventsCore.js
// at runtime the way this test file does. Instead it is generated by
// scripts/backgroundRunnerBuild.mjs, inlining that same core module beneath
// assets/background-runner.entry.js's OS-tick wiring. This test is the drift
// guard: it fails if anyone hand-edits the generated file, or edits a source
// without re-running `npm run build:background-runner`.
import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  CORE_PATH,
  ENTRY_PATH,
  OUTPUT_PATH,
  renderBackgroundRunner,
} from '../scripts/backgroundRunnerBuild.mjs'

describe('assets/background-runner.js (generated)', () => {
  it('matches a fresh render of backgroundEventsCore.js + background-runner.entry.js', () => {
    const core = readFileSync(CORE_PATH, 'utf8')
    const entry = readFileSync(ENTRY_PATH, 'utf8')
    const committed = readFileSync(OUTPUT_PATH, 'utf8')
    expect(committed).toBe(renderBackgroundRunner(core, entry))
  })

  it('never contains an export statement -- the isolated engine cannot parse one', () => {
    const committed = readFileSync(OUTPUT_PATH, 'utf8')
    expect(committed).not.toMatch(/^export /m)
  })
})
